# ========== 核心配置 ==========
title: "沙勒避难所-S.C.H.A.L.E."
url: "https://schale.us.kg"
timezone: Asia/Shanghai
permalink: /:title/

# ========== 安全配置 ==========
safe: true
exclude:
  - node_modules
  - Gemfile.lock
  - README.md

# ========== 评论系统 ==========
cusdis:
  app_id: "替换你的Cusdis应用ID"

# ========== 视觉配置 ==========
design:
  primary_color: "#2A5CAA"
  accent_color: "#5BC0EB"
  font_stack: "system-ui, -apple-system, Segoe UI, Roboto, Noto Sans SC, sans-serif"